/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.BankAccount;

/**
 *
 * @author josephchakola
 */
public class ViewBankAccount extends javax.swing.JPanel {

    /**
     * Creates new form ViewBankAccount
     */
    private final BankAccount bankAccount;
    public ViewBankAccount(BankAccount bankAccount) {
        initComponents();
        this.bankAccount = bankAccount;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        daField = new javax.swing.JTextField();
        atLabel = new javax.swing.JLabel();
        phField = new javax.swing.JTextField();
        fnField = new javax.swing.JTextField();
        daLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        atField = new javax.swing.JTextField();
        mainLabel = new javax.swing.JLabel();
        caLabel = new javax.swing.JLabel();
        phLabel = new javax.swing.JLabel();
        caField = new javax.swing.JTextField();

        daField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daFieldActionPerformed(evt);
            }
        });

        atLabel.setText("Account Type:");

        daLabel.setText("Debit Amount:");

        nameLabel.setText("Full Name:");

        atField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atFieldActionPerformed(evt);
            }
        });

        mainLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("View Bank Account");

        caLabel.setText("Credit Amount:");

        phLabel.setText("Phone Number:");

        caField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atLabel)
                    .addComponent(caLabel)
                    .addComponent(daLabel)
                    .addComponent(nameLabel)
                    .addComponent(phLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fnField)
                    .addComponent(atField)
                    .addComponent(daField)
                    .addComponent(caField)
                    .addComponent(phField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
            .addComponent(mainLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(fnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atLabel)
                            .addComponent(atField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(daLabel)
                            .addComponent(daField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caLabel))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phLabel)
                        .addComponent(phField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(288, 288, 288))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void daFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daFieldActionPerformed

    private void atFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atFieldActionPerformed

    private void caFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caFieldActionPerformed

    private void populate(){
       fnField.setText(bankAccount.getName());
       atField.setText(bankAccount.getAccountType());
       caField.setText(bankAccount.getCreditAmount());
       daField.setText(bankAccount.getDebitAmount());
       phField.setText(bankAccount.getPhoneNumber());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atField;
    private javax.swing.JLabel atLabel;
    private javax.swing.JTextField caField;
    private javax.swing.JLabel caLabel;
    private javax.swing.JTextField daField;
    private javax.swing.JLabel daLabel;
    private javax.swing.JTextField fnField;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phField;
    private javax.swing.JLabel phLabel;
    // End of variables declaration//GEN-END:variables
}
