/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Person;

/**
 *
 * @author josephchakola
 */
public class ViewPersonPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewPersonPanel
     */
    private final Person person;
    public ViewPersonPanel(Person person) {
        initComponents();
        this.person = person;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agField = new javax.swing.JTextField();
        lnLabel = new javax.swing.JLabel();
        gnField = new javax.swing.JTextField();
        fnField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        lnField = new javax.swing.JTextField();
        mainLabel = new javax.swing.JLabel();
        phLabel = new javax.swing.JLabel();
        genLabel = new javax.swing.JLabel();
        phField = new javax.swing.JTextField();

        agField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agFieldActionPerformed(evt);
            }
        });

        lnLabel.setText("Last Name:");

        ageLabel.setText("Age:");

        nameLabel.setText("First Name:");

        lnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnFieldActionPerformed(evt);
            }
        });

        mainLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("View a Person");

        phLabel.setText("Phone Number:");

        genLabel.setText("Gender:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lnLabel)
                            .addComponent(phLabel)
                            .addComponent(ageLabel)
                            .addComponent(nameLabel)
                            .addComponent(genLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fnField)
                            .addComponent(lnField)
                            .addComponent(agField)
                            .addComponent(phField)
                            .addComponent(gnField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(fnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnLabel)
                            .addComponent(lnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageLabel)
                            .addComponent(agField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(genLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(293, 293, 293))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agFieldActionPerformed

    private void lnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnFieldActionPerformed

    private void populate(){
        
        agField.setText(person.getAge());
        phField.setText(person.getPhoneNumber());
        fnField.setText(person.getFirstName());
        lnField.setText(person.getLastName());
        gnField.setText(person.getGender());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField fnField;
    private javax.swing.JLabel genLabel;
    private javax.swing.JTextField gnField;
    private javax.swing.JTextField lnField;
    private javax.swing.JLabel lnLabel;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phField;
    private javax.swing.JLabel phLabel;
    // End of variables declaration//GEN-END:variables
}
