/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author josephchakola
 */
public class CreationPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreationPanel
     */
    private final PersonDirectory directory;
    private final JSplitPane splitPane;
    public CreationPanel(PersonDirectory directory, JSplitPane splitPane) {
        initComponents();
        this.directory = directory;
        this.splitPane = splitPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        ssnField = new javax.swing.JTextField();
        liscenseField = new javax.swing.JTextField();
        waCityField = new javax.swing.JTextField();
        waStateField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        waUnitField = new javax.swing.JTextField();
        waStreetField = new javax.swing.JTextField();
        haCityField = new javax.swing.JTextField();
        haStateField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        haUnitField = new javax.swing.JTextField();
        haStreetField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(80, 80, 80));

        jLabel1.setBackground(new java.awt.Color(240, 240, 240));
        jLabel1.setForeground(new java.awt.Color(180, 180, 180));
        jLabel1.setText("First Name");

        jLabel2.setBackground(new java.awt.Color(240, 240, 240));
        jLabel2.setForeground(new java.awt.Color(180, 180, 180));
        jLabel2.setText("Last Name");

        jLabel3.setBackground(new java.awt.Color(240, 240, 240));
        jLabel3.setForeground(new java.awt.Color(180, 180, 180));
        jLabel3.setText("Social Security Number");

        jLabel4.setBackground(new java.awt.Color(240, 240, 240));
        jLabel4.setForeground(new java.awt.Color(180, 180, 180));
        jLabel4.setText("Liscense Number");

        lastNameField.setBackground(new java.awt.Color(180, 180, 180));
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        firstNameField.setBackground(new java.awt.Color(180, 180, 180));
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        ssnField.setBackground(new java.awt.Color(180, 180, 180));

        liscenseField.setBackground(new java.awt.Color(180, 180, 180));
        liscenseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liscenseFieldActionPerformed(evt);
            }
        });

        waCityField.setBackground(new java.awt.Color(180, 180, 180));
        waCityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waCityFieldActionPerformed(evt);
            }
        });

        waStateField.setBackground(new java.awt.Color(180, 180, 180));
        waStateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waStateFieldActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(240, 240, 240));
        jLabel5.setForeground(new java.awt.Color(180, 180, 180));
        jLabel5.setText("Street Address");

        jLabel6.setBackground(new java.awt.Color(240, 240, 240));
        jLabel6.setForeground(new java.awt.Color(180, 180, 180));
        jLabel6.setText("Unit Number");

        jLabel7.setBackground(new java.awt.Color(240, 240, 240));
        jLabel7.setForeground(new java.awt.Color(180, 180, 180));
        jLabel7.setText("City");

        jLabel8.setBackground(new java.awt.Color(240, 240, 240));
        jLabel8.setForeground(new java.awt.Color(180, 180, 180));
        jLabel8.setText("State");

        waUnitField.setBackground(new java.awt.Color(180, 180, 180));
        waUnitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waUnitFieldActionPerformed(evt);
            }
        });

        waStreetField.setBackground(new java.awt.Color(180, 180, 180));
        waStreetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waStreetFieldActionPerformed(evt);
            }
        });

        haCityField.setBackground(new java.awt.Color(180, 180, 180));

        haStateField.setBackground(new java.awt.Color(180, 180, 180));
        haStateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haStateFieldActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(240, 240, 240));
        jLabel9.setForeground(new java.awt.Color(180, 180, 180));
        jLabel9.setText("Street Address");

        jLabel10.setBackground(new java.awt.Color(240, 240, 240));
        jLabel10.setForeground(new java.awt.Color(180, 180, 180));
        jLabel10.setText("Unit Number");

        jLabel11.setBackground(new java.awt.Color(240, 240, 240));
        jLabel11.setForeground(new java.awt.Color(180, 180, 180));
        jLabel11.setText("City");

        jLabel12.setBackground(new java.awt.Color(240, 240, 240));
        jLabel12.setForeground(new java.awt.Color(180, 180, 180));
        jLabel12.setText("State");

        haUnitField.setBackground(new java.awt.Color(180, 180, 180));
        haUnitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haUnitFieldActionPerformed(evt);
            }
        });

        haStreetField.setBackground(new java.awt.Color(180, 180, 180));
        haStreetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haStreetFieldActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(240, 240, 240));
        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(180, 180, 180));
        jLabel13.setText("Work Address");

        jLabel14.setBackground(new java.awt.Color(240, 240, 240));
        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(180, 180, 180));
        jLabel14.setText("Home Address");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(waStreetField)
                            .addComponent(waCityField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(waUnitField)
                            .addComponent(waStateField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(firstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(ssnField))
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(lastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(liscenseField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(haStreetField)
                            .addComponent(haCityField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(haUnitField)
                            .addComponent(haStateField)
                            .addComponent(createButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liscenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waUnitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haUnitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haStateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(createButton)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void liscenseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liscenseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liscenseFieldActionPerformed

    private void waStateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waStateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waStateFieldActionPerformed

    private void waUnitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waUnitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waUnitFieldActionPerformed

    private void waStreetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waStreetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waStreetFieldActionPerformed

    private void haStateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haStateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haStateFieldActionPerformed

    private void haUnitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haUnitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haUnitFieldActionPerformed

    private void haStreetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haStreetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_haStreetFieldActionPerformed

    private void waCityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waCityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waCityFieldActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        if(firstNameField.getText().isBlank() || lastNameField.getText().isBlank() || ssnField.getText().isBlank() || liscenseField.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Please fill all the field");
        } else if(haCityField.getText().isBlank() || haStateField.getText().isBlank() || haStreetField.getText().isBlank() || haUnitField.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Please fill all the address field");
        } else if(waCityField.getText().isBlank() || waStateField.getText().isBlank() || waStreetField.getText().isBlank() || waUnitField.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Please fill all the address field");
        } else {
        Person p = new Person();
        p.setFirstName(firstNameField.getText());
        p.setLastName(lastNameField.getText());
        p.setSSN(ssnField.getText());
        p.setLiscenseNumber(liscenseField.getText());
        
        Address ha = new Address();
        ha.setCity(haCityField.getText());
        ha.setState(haStateField.getText());
        ha.setStreetAddress(haStreetField.getText());
        ha.setUnitNumber(haUnitField.getText());
        
        Address wa = new Address();
        wa.setCity(waCityField.getText());
        wa.setState(waStateField.getText());
        wa.setStreetAddress(waStreetField.getText());
        wa.setUnitNumber(waUnitField.getText());
        
        p.setHomeAddress(ha);
        p.setWorkAddress(wa);
        
        directory.addPerson(p);
        JOptionPane.showMessageDialog(this, "Person Saved.");
        reset();
        }
    }//GEN-LAST:event_createButtonActionPerformed
    private void reset(){
        firstNameField.setText("");
        lastNameField.setText("");
        liscenseField.setText("");
        ssnField.setText("");
        
        haCityField.setText("");
        haStateField.setText("");
        haStreetField.setText("");
        haUnitField.setText("");
        
        waCityField.setText("");
        waStateField.setText("");
        waStreetField.setText("");
        waUnitField.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField haCityField;
    private javax.swing.JTextField haStateField;
    private javax.swing.JTextField haStreetField;
    private javax.swing.JTextField haUnitField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField liscenseField;
    private javax.swing.JTextField ssnField;
    private javax.swing.JTextField waCityField;
    private javax.swing.JTextField waStateField;
    private javax.swing.JTextField waStreetField;
    private javax.swing.JTextField waUnitField;
    // End of variables declaration//GEN-END:variables
}
